Correct workflow

diff --git a/.github/workflows/python-package.yml b/.github/workflows/python-package.yml
--- a/.github/workflows/python-package.yml
+++ b/.github/workflows/python-package.yml
@@ -28,72 +28,74 @@ jobs:
         COVERAGE_FILE: ".coverage.${{ matrix.env }}.${{ matrix.python-version }}"
 
     steps:
-    - uses: actions/checkout@v2
-    - name: Set up Python ${{ matrix.python-version }}
-      uses: actions/setup-python@v2
-      with:
-        python-version: ${{ matrix.python-version }}
-    - name: Install dependencies
-      run: |
-        sudo apt update && sudo apt install libudunits2-dev libproj-dev libeccodes0 libeccodes-dev libnetcdf-dev\
+      #----------------------------------------------
+      #           check-out repo
+      #----------------------------------------------
+      - name: Check out repository
+        uses: actions/checkout@v3
 
-    #----------------------------------------------
-    #  --- configure poetry & install project  ----
-    #----------------------------------------------
-    - name: Install Poetry
-      uses: snok/install-poetry@v1
-      with:
-        virtualenvs-create: true
-        virtualenvs-in-project: true
+      - name: Install dependencies
+        run: |
+          apt-get update
+          apt get-install libudunits2-dev libproj-dev libeccodes0 libeccodes-dev libnetcdf-dev\
 
-    - name: Load cached venv (if cache exists)
-      id: cached-poetry-dependencies
-      uses: actions/cache@v3
-      with:
-        path: .venv
-        key: venv-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('**/pyproject.toml') }}
+      #----------------------------------------------
+      #  --- configure poetry & install project  ----
+      #----------------------------------------------
+      - name: Install Poetry
+        uses: snok/install-poetry@v1
+        with:
+          virtualenvs-create: true
+          virtualenvs-in-project: true
 
-    - name: Install dependencies (if venv cache is not found)
-      if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
-      run: poetry install --no-interaction --no-root --only main,test
+      - name: Load cached venv (if cache exists)
+        id: cached-poetry-dependencies
+        uses: actions/cache@v3
+        with:
+          path: .venv
+          key: venv-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('**/pyproject.toml') }}
 
-    - name: Install the project itself
-      run: poetry install --no-interaction --only-root
+      - name: Install dependencies (if venv cache is not found)
+        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
+        run: poetry install --no-interaction --no-root --only main,test
 
-    #----------------------------------------------
-    #      run test suite and report coverage
-    #----------------------------------------------
-    - name: Run tests
-      run: |
-        poetry run pytest
+      - name: Install the project itself
+        run: poetry install --no-interaction --only-root
 
-    - name: Coveralls
-      if: ${{ matrix.python-version == 3.8 }}
-      run: |
-        export COVERALLS_REPO_TOKEN=${{secrets.COVERALLS_REPO_TOKEN}}
-        poetry run coveralls
+      #----------------------------------------------
+      #      run test suite and report coverage
+      #----------------------------------------------
+      - name: Run tests
+        run: |
+          poetry run pytest -n auto
 
-    - name: Create documentation
-      if: ${{ matrix.python-version == 3.8 }}
-      run: |
-        cd docs
-        make html
-    - name: Commit documentation changes
-      if: ${{ matrix.python-version == 3.8 }}
-      run: |
-        git clone https://github.com/metno/pysurfex.git --branch gh-pages --single-branch gh-pages
-        cp -r docs/build/html/* gh-pages/
-        cd gh-pages
-        git config --local user.email "action@github.com"
-        git config --local user.name "GitHub Action"
-        git add .
-        git commit -m "Update documentation" -a || true
-        # The above command will fail if no changes were present, so we ignore
-        # the return code.
-    - name: Push changes
-      if: ${{ matrix.python-version == 3.8 }} && github.repository == 'metno/pysurfex'
-      uses: ad-m/github-push-action@master
-      with:
-        branch: gh-pages
-        directory: gh-pages
-        github_token: ${{ secrets.GITHUB_TOKEN }}
+      - name: Coveralls
+        if: ${{ matrix.python-version == 3.8 }}
+        run: |
+          export COVERALLS_REPO_TOKEN=${{secrets.COVERALLS_REPO_TOKEN}}
+          poetry run coveralls
+
+      - name: Create documentation
+        if: ${{ matrix.python-version == 3.8 }}
+        run: |
+          cd docs
+          make html
+      - name: Commit documentation changes
+        if: ${{ matrix.python-version == 3.8 }}
+        run: |
+          git clone https://github.com/metno/pysurfex.git --branch gh-pages --single-branch gh-pages
+          cp -r docs/build/html/* gh-pages/
+          cd gh-pages
+          git config --local user.email "action@github.com"
+          git config --local user.name "GitHub Action"
+          git add .
+          git commit -m "Update documentation" -a || true
+          # The above command will fail if no changes were present, so we ignore
+          # the return code.
+      - name: Push changes
+        if: ${{ matrix.python-version == 3.8 }} && github.repository == 'metno/pysurfex'
+        uses: ad-m/github-push-action@master
+        with:
+          branch: gh-pages
+          directory: gh-pages
+          github_token: ${{ secrets.GITHUB_TOKEN }}
